-- Insert sample products for testing
INSERT INTO public.products (name, slug, price, compare_at_price, description, category, wood_type, images, stock_quantity, low_stock_threshold, is_active, is_featured, is_trending, care_instructions, shipping_info)
VALUES
  (
    'Heritage Memorial Urn',
    'heritage-memorial-urn',
    489,
    549,
    'A beautifully handcrafted memorial urn made from premium black walnut. Each piece is meticulously carved to honor the memory of your loved ones with timeless elegance.',
    'Memorial Urns',
    'Black Walnut',
    ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'],
    15,
    5,
    true,
    true,
    false,
    'Dust regularly with a soft, dry cloth. Avoid direct sunlight and moisture.',
    'Free shipping on orders over $200. Ships within 3-5 business days.'
  ),
  (
    'Eternal Rest Companion Urn',
    'eternal-rest-companion-urn',
    679,
    749,
    'A stunning companion urn designed for two, crafted from rich cherry wood with hand-carved floral motifs. Perfect for couples who wish to remain together eternally.',
    'Memorial Urns',
    'Cherry',
    ARRAY['https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=800'],
    8,
    3,
    true,
    true,
    true,
    'Polish with natural wood oil every 6 months to maintain luster.',
    'Free shipping. Handcrafted to order, ships within 7-10 business days.'
  ),
  (
    'Serenity Keepsake Urn',
    'serenity-keepsake-urn',
    189,
    null,
    'A small but elegant keepsake urn perfect for sharing memories among family members. Made from maple wood with a satin finish.',
    'Memorial Urns',
    'Maple',
    ARRAY['https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=800'],
    25,
    5,
    true,
    false,
    true,
    'Wipe clean with a soft cloth. Keep away from extreme temperatures.',
    'Ships within 2-3 business days.'
  ),
  (
    'Artisan Carving Mallet',
    'artisan-carving-mallet',
    145,
    165,
    'Professional-grade carving mallet crafted from dense lignum vitae. Perfect balance and weight for precision woodworking.',
    'Woodworking Tools',
    'Oak',
    ARRAY['https://images.unsplash.com/photo-1586864387789-628af9feed72?w=800'],
    42,
    10,
    true,
    false,
    false,
    'Oil the handle periodically with linseed oil.',
    'Ships within 1-2 business days.'
  ),
  (
    'Master Chisel Set',
    'master-chisel-set',
    289,
    329,
    'A complete set of 8 hand-forged chisels with ergonomic oak handles. Each blade is hardened to hold a razor-sharp edge.',
    'Woodworking Tools',
    'Oak',
    ARRAY['https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800'],
    18,
    5,
    true,
    true,
    false,
    'Store in dry conditions. Sharpen regularly for best results.',
    'Free shipping. Ships within 3-5 business days.'
  ),
  (
    'Nautical Compass Rose',
    'nautical-compass-rose',
    329,
    null,
    'A stunning hand-carved compass rose wall piece made from reclaimed teak. Perfect for adding maritime charm to any space.',
    'Nautical Decor',
    'Teak',
    ARRAY['https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?w=800'],
    12,
    3,
    true,
    true,
    true,
    'Suitable for indoor use. Dust with soft cloth.',
    'Ships within 5-7 business days.'
  ),
  (
    'Ships Wheel Wall Art',
    'ships-wheel-wall-art',
    459,
    519,
    'An authentic replica ships wheel crafted from aged mahogany. Each piece tells a story of maritime adventure and craftsmanship.',
    'Nautical Decor',
    'Mahogany',
    ARRAY['https://images.unsplash.com/photo-1534190239940-9ba8944ea261?w=800'],
    6,
    2,
    true,
    false,
    true,
    'Display away from direct sunlight. Clean with dry cloth only.',
    'Free shipping. Ships within 7-10 business days.'
  ),
  (
    'Mountain Landscape Carving',
    'mountain-landscape-carving',
    599,
    null,
    'A breathtaking 3D landscape carving depicting mountain peaks at sunset. Hand-carved from a single piece of black walnut.',
    'Wall Art',
    'Black Walnut',
    ARRAY['https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800'],
    4,
    2,
    true,
    true,
    false,
    'Dust gently. Avoid humid environments.',
    'Ships within 10-14 business days due to intricate craftsmanship.'
  ),
  (
    'Wildlife Portrait - Eagle',
    'wildlife-portrait-eagle',
    389,
    429,
    'A majestic eagle portrait carved in stunning detail from cherry wood. The perfect statement piece for nature enthusiasts.',
    'Wall Art',
    'Cherry',
    ARRAY['https://images.unsplash.com/photo-1578926288207-a90a5366759d?w=800'],
    9,
    3,
    true,
    false,
    false,
    'Keep in climate-controlled environment for best preservation.',
    'Ships within 5-7 business days.'
  ),
  (
    'Celtic Knot Box',
    'celtic-knot-box',
    125,
    null,
    'An intricately carved jewelry box featuring traditional Celtic knotwork. Made from solid maple with a velvet-lined interior.',
    'Nautical Decor',
    'Maple',
    ARRAY['https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800'],
    35,
    8,
    true,
    false,
    true,
    'Clean with soft dry cloth. Store in dry location.',
    'Ships within 2-3 business days.'
  );